---
title: "Bienvenidos al San Carlos R User Group (SCRUG)"
---

¡Hola y bienvenido!

Somos un grupo de entusiastas de R en la Zona Norte de Costa Rica, abierto a
cualquier participante de Latinoamérica. Nos reunimos para aprender, compartir
y colaborar en proyectos relacionados con el análisis de datos y el lenguaje
de programación R.

## ¿Qué hacemos?

Organizamos reuniones, talleres y eventos para:

* **Aprender R:** Desde los conceptos básicos hasta temas avanzados.
* **Compartir conocimiento:** Presentamos nuestros proyectos y aprendemos de los
demás.
* **Colaborar:** Trabajamos juntos en proyectos de código abierto y análisis de
datos.
* **Crecer la comunidad:** Creamos un espacio amigable y de apoyo para todos los
interesados en R.

## ¿Cómo participar?

¡Es muy fácil! Puedes unirte a nosotros de las siguientes maneras:

* **Unete a nuestro grupo en Meetup:** [San Carlos R User Group en
Meetup.com](https://www.meetup.com/es-ES/San-Carlos-R-User-Group/) para
enterarte de nuestras próximas reuniones.
* **Mira nuestras reuniones pasadas:** [Lista de reproducción de SCRUG en el
canal de Data
Latam](https://www.youtube.com/playlist?list=PLZpKvQTlfyCKuTzKZ3N7LOyGwm4Ub1ry3)
donde puedes ver grabaciones de nuestras reuniones pasadas.
* **Explora nuestro material de aprendizaje:** [Material para
autodidactas](material-para-autodidactas.html) para empezar a aprender R a tu
propio ritmo.

No importa si eres un principiante o un experto, ¡toda persona interesada es
bienvenida!

# Agenda para 2026

Esta lista son ideas iniciales. Si tienes alguna idea o si quires ser el
moderador para una de las sesiones avisanos! Sería buenisimo incluirte como
moderador. Asimismo si tienes ideas para temas, o sugerencias para cambiar
alguna haznoslo saber, el programa es una idea inicial que esta abierta a
cambios.

El enfoque de la temática es "R como lenguaje de producción" para reflejar los
avances del lenguaje y el ecosistema R y la comunidad alrededor del lenguaje.
2025 vió la llegada por ejemplo de `rv` lo que nos permite llevar
reproducibilidad y despliegue al siguiente nivel.

Para inscribirte visita: [Meetup
SCRUG](https://www.meetup.com/es-ES/San-Carlos-R-User-Group/). Todas las
reuniones son en linea (remotas via Zoom).

| Fecha | Tema |  Relevancia |
| :----------- | :---------- | :--- |
| Febrero 26 | Gestionar paquetes R con `rv` |  [El gestor de paquete `rv`](https://a2-ai.github.io/rv-docs/) fue creado por la gente en a2-ai y ha visto una adopción muy rapida porque nos da un gestor de paquetes que tiene carecteristicas que Astral `uv` nos da en python. Vamos a arrancar con una introduccion para explicar la importancia de un gestor de versiones de paquetes y mostrar su uso con ejemplos prácticos. |
| Abril 30 | Crear un servidor MCP con R para usar funcionaes en soluciones genAI | EL uso serio de LLM para resolver casos de uso de ciencia e industria requiere poder definir y darle a tus agentes la posibilidad de acceder funciones. Damos una introduccion explicando MCP como una de las formas para trabajar con funciones y algunos ejemplos practicos para crearlos  |
| Junio 25  | genAI para convertir texto en datos estructurados | Una de las grandes bondades de genAi en aplicaciones de analisis de datos es que nos permite convertir datos no estructurados a tablas estructuradas. En particular lo usamos para extraer datos de texto, pero tambien ayuda para recopilar información disponible en audio y video. Damos una breve introducción para enfocarnos en ejemplos practicos. |
| Agosto 27 | Uso de docker para poner codigo R en produccion | Docker es la tecnologia en uso por defecto para desplegar software y al ser agnostico del lenguaje en uso permite un alto grade de interoperabilidad en soluciones de datos. Vamos a comenzar desde el principio, con una breve introduccion a lo que es Docker, para que sirve y como lo podemos usar para desplegar codigo R. |
|  Octubre 29| Llevar codigo R a API's en producción con `plumber2` | Entre los paquetes que facilitan escribir API's (servicios web) con R, plumber ha visto una gran adopción. Y sus maintaners decidieron re-escribirlo para modernizar y optimizar el codigo, introduciendo entre otras `httr2`. En esta sesion vamos a comenzar desde el principio, explicando porque es util poder escribir API y mostrar de una forma practica como hacerlo con plumber2  |

### Formato

Para este año proponemos el siguiente formato.

 - 5 min. Bienvenida (dar algo de tiempo para que gente llegue, despues cerramos
   la sala)
 - 20 min. Charla y demo con el contenido
 - 15 min. Discusión.

Si quieres participar por favor llega a tiempo. Buscamos publicar la grabación
de la charla y demo, pero no de la discusión para que todos se sientan comodos
en participar y hacer cualquier pregunta que tengan.
