---
title: "Introducción a R"
---

Bienvenido al Grupo de Usuarios R en San Carlos, Costa Rica. Si buscas unirte
al grupo, o si quieres ver las reuniones futuras (o pasadas) mira aqui:
[www.meetup.com/San-Carlos-R-User-Group/](http://www.meetup.com/San-Carlos-R-User-Group/).

En esta pagina presentamos información general y esta abierto a todos los
comentarios y sugerencias para mejorarlo!

## Instalar R (para participar en los talleres)
Para participar en los talleres necesitas tener instalado una versión reciente
de [R](https://cran.rstudio.com/) y de [RStudio
Desktop](https://www.rstudio.com/products/rstudio/download/).  No importa si
usas MS Windows, Mac OSX or Linux en tu computador, para cada uno hay versiones
correspondientes de los programas.

## Recursos para aprender R
Hay muchos recursos sobre R y bastantes en español. El recurso más recomendado
actualmente es el libro [R para Ciencia de Datos](https://es.r4ds.hadley.nz/),
una guía moderna, completa y gratuita.

Quizás la forma más interactiva (divertida) para comenzar es usando [swirl](https://swirlstats.com/students.html) a través de su traducción al español [swirl-spa](https://github.com/alcideschaux/swirl-spa). Esto te dará un buen punto de partida para empezar a explorar R y acostumbrarte a la sintaxis del lenguaje desde la propia consola.

Pero posiblemente lo mas importante es que busques un problema para analizar que
te guste o que sea necesario para tu trabajo/estudio/saludo mental. Mantenemos
una [pagina con fuentes de datos](fuentes-de-datos.html) donde coleccionamos
datos sobre San Carlos, Costa Rica, y recursos mas a internacional.

### Algunas hojas de referencia básicas en español
* [Transformación de Datos](https://rstudio.github.io/cheatsheets/translations/spanish/data-transformation-spanish.pdf)
* [Quarto](https://rstudio.github.io/cheatsheets/translations/spanish/quarto-spanish.pdf)
* [Shiny](https://rstudio.github.io/cheatsheets/translations/spanish/shiny-spanish.pdf)
* [Desarrollo de Paquetes](https://rstudio.github.io/cheatsheets/translations/spanish/package-development-spanish.pdf)
* [Visualización de Datos](https://rstudio.github.io/cheatsheets/translations/spanish/ggplot2-spanish.pdf)

## Lista curada por tipo de tarea

 - Hay una lista curada por tipo de tarea que llaman los [CRAN Task Views](https://cran.r-project.org/web/views/). Lo mantiene la comunidad R y da una entrada relativamente actualizada para cada dominio de expertise.
 - El site de [R-Bloggers](https://www.r-bloggers.com) tiene una historia larga como agregador de blog-posts con temas R.
 - El [R-Universe](https://r-universe.dev/search) es un lugar que lo mantiene [R-OpenSci](https://ropensci.org/r-universe/) para descubrir, desarrollar y publicar paquetes R.
